### ISSUE TITLE
Interesting work

### ISSUE THREAD

**Issue by mrT23** [SlongLiu/query2labels#1]
Your work looks interesting and usefull.

Any prediction when a code will be released ?

**Comment by SlongLiu** [comment]
Thanks for your interest. 

We are cleaning the code, and I expect to release it before the next weekend.

**Comment by NingMa-AI** [comment]
Looking forward to the released code!

**Comment by 123675** [comment]
Looking forward to the released code!

**Comment by bakulaibuji** [comment]
I am really interested your work, looking forward to the released code!
