### ISSUE TITLE
Do you have any code or suggestions for visualization?

### ISSUE THREAD

**Issue by wzn123** [SlongLiu/query2labels#12]
Hi, I am student who current doing a deep learning project, I am wondering do you have any code or suggestion for visualization in figure 1, especially the part in the center. How did you implement it. The figure shows below. Looking forward to your reply. Thanks in advance. 
![image](https://user-images.githubusercontent.com/46923558/143524249-01473b33-1798-43b0-861d-8015dc5230ef.png)

**Comment by SlongLiu** [comment]
The visualization is simple and direct. You need to save the multi-head attention maps of the cross-attention for the input image. You may need to go deep in the code of the `forward` method of the `MultiheadAttention` class.

**Comment by wzn123** [comment]
Got it. Thanks for your reply.
