### ISSUE TITLE
How to get this train_label_vectors_coco14.npy？

### ISSUE THREAD

**Issue by 123675** [SlongLiu/query2labels#13]
train_label_vectors_coco14.npy
val_label_vectors_coco14.npy

**Comment by sorrowyn** [comment]
https://github.com/SlongLiu/query2labels/blob/main/lib/dataset/cocodataset.py#L32

        if os.path.exists(self.labels_path):
            self.labels = np.load(self.labels_path).astype(np.float64)
            self.labels = (self.labels > 0).astype(np.float64)
        else:
            print("No preprocessed label file found in {}.".format(self.labels_path))
            l = len(self.coco)
            for i in tqdm(range(l)):
                item = self.coco[i]
                # print(i)
                categories = self.getCategoryList(item[1])
                label = self.getLabelVector(categories)
                self.labels.append(label)
            self.save_datalabels(labels_path)
        # import ipdb; ipdb.set_trace()``

**Comment by SlongLiu** [comment]
Thanks for the reply of @sorrowyn. It's the preprocessing code that can generate the needed .npy files.
We have provided the preprocessed data in https://github.com/SlongLiu/query2labels/tree/main/data/coco as well.

**Comment by 123675** [comment]
Thank you for your response!
