### ISSUE TITLE
TResNet pre-trained on ImageNet-22k

### ISSUE THREAD

**Issue by sunfeng2016** [SlongLiu/query2labels#14]
Thank you very much for your work. I have the idea of following it to my own work, but I can't find the pre-trained TResNet backbones on ImageNet-22k dataset with input resolution of 224. I would appreciate it if you can share.

**Comment by sorrowyn** [comment]
This document can answer your question .
https://github.com/Alibaba-MIIL/ImageNet21K/blob/main/MODEL_ZOO.md

tresnet_l_v2_miil_21k.pth:
https://miil-public-eu.oss-eu-central-1.aliyuncs.com/model-zoo/ImageNet_21K_P/models/tresnet_l_v2_miil_21k.pth
