### ISSUE TITLE
AttributeError while testing

### ISSUE THREAD

**Issue by Nahr-C** [SlongLiu/query2labels#15]
Hi i am trying to test a pretrained model but an error occurs, i`m new to deep learning, can you please tell me how to fix it?
![2021-12-14 05-08-24屏幕截图](https://user-images.githubusercontent.com/78709310/145931668-5a56d885-1da5-4c70-a2e0-14d4308ff92a.png)

**Comment by sorrowyn** [comment]
```
parser.add_argument('--cutout', action='store_true', default=False,
                        help='apply cutout')
```
You can reference this [file](https://github.com/SlongLiu/query2labels/blob/main/main_mlc.py)
