### ISSUE TITLE
an trian error ：

### ISSUE THREAD

**Issue by fsted** [SlongLiu/query2labels#19]
Really an excellent paper，
but I face an train error ：
`subprocess.CalledProcessError: Command '['/home/anaconda3/envs/ql/bin/python，, '-u', 'main_mlc.py', '--local_rank=3', '--backbone', 'resnet101', '--dataname', 'voc07', '--batch-size', '64', '--print-freq', '100', '--world-size', '1', '--rank', '0', '--dist-url', 'tcp://127.0.0.1:3717', '--gamma_pos', '0', '--gamma_neg', '2', '--dtgfl', '--epochs', '80', '--lr', '1e-4', '--optim', 'AdamW', '--pretrained', '--num_class', '20', '--img_size', '448', '--weight-decay', '1e-2', '--cutout', '--n_holes', '1', '--cut_fact', '0.5', '--hidden_dim', '2048', '--dim_feedforward', '8192', '--enc_layers', '1', '--dec_layers', '2', '--nheads', '4', '--early-stop', '--amp']' returned non-zero exit status 1`
how can I do it ，Thanks

**Comment by SlongLiu** [comment]
Please provide the command you used and more logs.

**Comment by fsted** [comment]
> Please provide the command you used and more logs.

I know there's something wrong there. There's something wrong with my CUDA production😄
and then，I have another question is, does the project include code that can reproduce the visualization results in the paper？It looks great
