### ISSUE TITLE
结果随机性

### ISSUE THREAD

**Issue by vivian27chen** [SlongLiu/query2labels#25]
我试跑了三次VOC2007，发现结果不一样，差距在0.5内。请问是否有方法消除这种随机性？

**Comment by sorrowyn** [comment]
`    parser.add_argument('--seed', default=None, type=int,
                        help='seed for initializing training. ')`

`--seed 1`

**Comment by vivian27chen** [comment]
> ` parser.add_argument('--seed', default=None, type=int, help='seed for initializing training. ')`
> 
> `--seed 1`

非常感谢！
