### ISSUE TITLE
Do you have Tensorflow code of AsymmetricLoss?

### ISSUE THREAD

**Issue by guotong1988** [SlongLiu/query2labels#28]
Thank you very much!

**Comment by sorrowyn** [comment]
You can refer to this method. 
[https://github.com/Alibaba-MIIL/ASL](url) or [https://github.com/SmilingWolf/SW-CV-ModelZoo/blob/c2f54b0c24653b855025ec9907dca8b03fd6a85d/Losses/ASL.py](url)

**Comment by guotong1988** [comment]
https://github.com/SmilingWolf/SW-CV-ModelZoo/blob/main/Losses/ASL.py
