### ISSUE TITLE
config file

### ISSUE THREAD

**Issue by ShijianXu** [SlongLiu/query2labels#3]
Thank you for your work. May I ask where can I find the config file?

**Comment by SlongLiu** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    The config files are put together with the pretrained models: https://cloud.tsinghua.edu.cn/d/a1560cd327dc45d0ad8e/
    
        
            
        
    
    
     
    
        
                    
            
                
                    
                            
                                
                            
                            
                                Shilong Liu
                                    PhD Student.
                            
                            
                                
                            
                    
                        
                            
                                    Depart. of CST, Tsinghua University.
                                    +86 18811029269
                                    ***@***.***
                                    
                                    100084
                                    
                            
                        
                
            
        
        
    
    
        签名由
        网易邮箱大师
        定制
    
 

    On 8/23/2021 14:37，XU ***@***.***> wrote： 



Thank you for your work. May I ask where can I find the config file?

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by ShijianXu** [comment]
Thanks!
