### ISSUE TITLE
AttributeError: 'Namespace' object has no attribute 'arch' in main_mlc.py

### ISSUE THREAD

**Issue by macqueen09** [SlongLiu/query2labels#31]
thank for your job.
I find: 
`[05/31 10:42:36.162]: 0 | Set best mAP 70.74814334530387 in ep 0
[05/31 10:42:36.162]:    | best regular mAP 70.74814334530387 in ep 0
Traceback (most recent call last):
  File "main_mlc.py", line 727, in <module>
    main()
  File "main_mlc.py", line 224, in main
    return main_worker(args, logger)
  File "main_mlc.py", line 407, in main_worker
    'arch': args.arch,
AttributeError: 'Namespace' object has no attribute 'arch'`

there is no arch in main_mlc.py and input argparse 
but it could be found in  q2l_infer.py

so, is that some code error in this commit when I retrain this model in coco-dataset

(by the way, there is another error:     training with Q2L-SwinL-384 has position error in transformer part,
resnet101 is fine)

**Comment by sorrowyn** [comment]
add in `main_mlc.py`
`available_models = ['Q2L-R101-448', 'Q2L-R101-576', 'Q2L-TResL-448', 'Q2L-TResL_22k-448', 'Q2L-SwinL-384', 'Q2L-CvT_w24-384']`

`    parser.add_argument('-a', '--arch', metavar='ARCH', default='Q2L-R101-448',
                        choices=available_models,
                        help='model architecture: ' +' | '.join(available_models) +
                            ' (default: Q2L-R101-448)')`
