### ISSUE TITLE
Pre-trained weights over Pascal VOC 2012

### ISSUE THREAD

**Issue by lucasdavid** [SlongLiu/query2labels#33]
Hello. Thank you very much for making the code available.

I was wondering if you still have the pre-trained weights over Pascal VOC 2012 dataset, and if those could be added here as well.
As far as I can tell, the ones in the README.md refer to the COCO dataset, right? Moreover, their links seem to be broken.

Cheers,

**Comment by JakobWong** [comment]
Would like to ask for the same.

**Comment by SlongLiu** [comment]
Yes, we only released the model for COCO. We will consider releasing the VOC models later.
Thanks for pointing out the broken links on Tsinghua Cloud. we fixed them just now.

**Comment by manuelknott** [comment]
Hi, are pretrained weights for Pascal VOC shared in the meantime? Would love to use them as well

**Comment by aooating** [comment]
Looking forward to the release of the VOC model!
