### ISSUE TITLE
Question about the SLCutoutPIL.

### ISSUE THREAD

**Issue by jasonseu** [SlongLiu/query2labels#35]
Hi, thanks for your impressive work. I have a question about the `SLCoutoutPIL` with the training parameters `--cutout --n_holes 1 --cut_fact 0.5`. According to your code `train_data_transform_list.insert(1, SLCutoutPIL(n_holes=args.n_holes, length=args.length))`, the cutout in your augmentation actually fill only a rectangle region with `height=1` and `width=1`, which is a very small region. Is that right?

**Comment by sorrowyn** [comment]
![图片](https://user-images.githubusercontent.com/19569162/181878084-a0e2ac9e-4bc5-408d-bc7c-6b9a82d7d195.png)

**Comment by jasonseu** [comment]
Yes, setting the length=224 can cut out a considerable region. But the author recommends to use the default setting -1 as the length of the holes according to the code in [this line](https://github.com/SlongLiu/query2labels/blob/55eb05064f4badbe03423b79e5c9d143da2dff2e/main_mlc.py#L119).

**Comment by sorrowyn** [comment]
> 

I recommend using the length=224.

**Comment by jasonseu** [comment]
Ok, thanks for your suggestion.
