### ISSUE TITLE
training log

### ISSUE THREAD

**Issue by WasedaMagina** [SlongLiu/query2labels#5]
Hi, query2label is an interesting project. I'm working on re-implementing it. However, I don't know if I got it right until I receive the final evaluation result. Therefore, would you mind releasing the training log?  It will be very helpful. Thanks.

**Comment by SlongLiu** [comment]
Thanks for your interest and suggestions. 
The training logs are updated to the shared link of model zoos and could be visited by https://cloud.tsinghua.edu.cn/d/a1560cd327dc45d0ad8e/?p=%2FQ2L-logs&mode=list

**Comment by originalchi** [comment]
@WasedaMagina Would you give me a training script pls? Thanks.

**Comment by lucasdavid** [comment]
The link seems to be broken. Can we access it from other source?
