### ISSUE TITLE
请问使用COCO2014数据集时设置的阈值是多少？

### ISSUE THREAD

**Issue by lzy5967** [SlongLiu/query2labels#55]
在代码中没有看到具体的阈值是多少，想问一下判断正样本的逻辑是什么？望回复T T

**Comment by Zhong1015** [comment]
正常判断是0.5，如果你要复现CP,CR,CF1,OP,OR,OF1的值需要自己去根据模型在infer里调整，作者提供的448 resnet101的那个模型阈值为0.823时和原论文的一致
