### ISSUE TITLE
Apply to custom datasets

### ISSUE THREAD

**Issue by 834799106** [SlongLiu/query2labels#7]
Thank you very much for your work. I have the idea of applying it to my own data set, but it is not friendly to laypeople. I don't know where to start

**Comment by vivian27chen** [comment]
Have you solved this problem? I find this problem in my epoch 8 while training.
The loss is NaN and it breaks

**Comment by stellating** [comment]
I meet the same problem in epoch 8 while training. Anyone solved this problem?

**Comment by nullgogo** [comment]
验证集里标签不全的话，mAP会出现nan。
解决方法
（1）训练集和验证集划分的时候，保证验证集的标签完整；
（2）metric.py里在计算ap的时候，如果验证集里没有的标签，ap会是nan，所以最方便的方法是把ap为nan的过滤掉，在50行前面加上，
          if ap != ap:
             continue
通过上面两种方法都可以解决nan的问题，但更倾向于第一种方法。

**Comment by JiangdongWang123** [comment]
> Have you solved this problem? I find this problem in my epoch 8 while training. The loss is NaN and it breaks

Have you solved the problem? I have the same problem.

**Comment by djdll** [comment]
最近在研究这篇论文，nan的问题很多人遇到，这里给大家一个解决方法，首先原因是map计算过程出现了问题如上面用户提供的方法类似，lib/utils/metric.py添加代码true_num计算后添加
```
if true_num == 0:
            aps.append(0)  # 如果没有正样本，直接添加0
            continue
```
意思就是验证集如果没有正确数量直接置为0跳出，否则验证集数据不全就会nan
