### ISSUE TITLE
Cannot train

### ISSUE THREAD

**Issue by chauminhnguyen** [SlongLiu/query2labels#9]
I really appreciate your work and I want to train query2label on custom dataset. However, when I run the train code and the code showed the line:

```
/usr/local/lib/python3.7/dist-packages/torch/utils/data/dataloader.py:481: UserWarning: This DataLoader will create 30 worker processes in total. Our suggested max number of worker in current system is 2, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
  cpuset_checked))
[11/03 06:48:25.411]: lr:4.000000000000002e-06
^C
```

Then code stopped without telling error. I don't know how to fix it. I hope you reply to me soon.

**Comment by sorrowyn** [comment]
pytorch < 1.9

**Comment by SlongLiu** [comment]
We use a large number of workers (32) for data loader by default, which may cause a heavy burden for some systems. You can reduce the number of workers by changing `-j` or `--workers` arg.
